dist: xenial
language: python
python:
  - '2.7'
  - '3.6'
  - '3.7'
install:
  - pip install tox-travis
script:
  - tox
addons:
  apt:
    packages:
    - rpm
deploy:
  - provider: pypi
    user: theforeman
    password:
      secure: dr/AiEM63RRjRz8V6n9c851644dEMwH7WtrSiSFr3UMJGpQVvp0TPx42E7QEvTRzLoTfCCZOX9vA3uQfmU6g3cIM2aamXhk43AQdPJbTcr2ZQm0FH3F8IGtexxkkZJ61RqbemHz/hXQHUZtxS3M2wN3SHIzNXOUFkcoNpSQmUHb6+0V2wnnoSBmTpwvGYOkMVFt9DA6VH+OGIQbem+5YtWpciH0TICgAjmbhZTIkPwjHwtfc6Jl0+dghbW//cP7mQ3cMtni+gmqEPxhv8zHOkFMUmCL1a4zEZFESEew4gAtJ3nwRAUH0TOLS3og6qeVHwRJzpK4RJHFEhOopO3HNNmrSvIfXcxuINNCdkoJglRSRNAO2McVau2okTeh+3gWuZ6btV19ySA3Zxpn5xUpcjDuJaS8/HG28+j+r1oO2LYvW2NbYcuTb3FVzCGTyBrlqXfTTFUlONpQdfBh1cFPvzQTrI7uYtYuZS7G06DaN9SmzYTUH/RJ2uy9m3N/JUm/apPzRkbwI7wBoVqfSzND2+lSM5Bk4SReDDkO5vwNbRbvXg5yOIfSHt+hoMMU3yh+ruRjyY3cgsYW7xyFVprKmTWPA5etFiFZ0oa3i+F+OGBuZY5YeHQ7PNljB8t+5+ODVfEs1soPw9eJMkA365wdhvNMf+GxOoEDVkfQqP0bo4tw=
    on:
      tags: true
      python: '3.6'
